app/components/Button/Button.tsx, app/components/Input/Input.tsx, app/components/Label/Label.tsx, app/components/Listing/Amount.tsx, app/components/Listing/PaymentMethod.tsx, app/components/Listing/Summary.tsx, app/components/Loading.tsx, app/components/MarginSwitcher.tsx, app/components/Select/BankSelect.tsx, app/components/Select/CurrencySelect.tsx, app/components/Select/TokenSelect.tsx, app/components/Textarea/Textarea.tsx, app/pages/_app.tsx, app/pages/index.tsx, app/pages/sell/index.tsx
- Update Label component styles
- Update Button component style, now it's w-full by default
- Create Empty state with a message for Connect to Polygon
- Create a Loading component with an animated spinner
- Sell flow Desktop improvements
=> Improvements week 52

app/.prettierrc, app/components/Avatar.tsx, app/components/Button/Button.tsx, app/next.config.js, app/pages/_app.tsx, app/pages/index.tsx, app/pages/sell/index.tsx
- Improve responsive table
- Create rounded button
- Change _app.tsx header
- Create Avatar component
Mobile
Desktop
=> Table improvements

app/components/Button/Button.tsx, app/components/Buy/Amount.tsx, app/components/Buy/ClipboardText.tsx, app/components/Buy/Compleated.tsx, app/components/Buy/CopyPastListItem.tsx, app/components/Buy/Payment.tsx, app/components/Buy/Release.tsx, app/components/Buy/Summary.tsx, app/components/Input/InputToken.tsx, app/components/Listing/StepLayout.tsx, app/components/Listing/Summary.tsx, app/components/SectionHeading/h2.tsx, app/models/types.ts, app/pages/buy/index.tsx, app/pages/index.tsx
- Create Buy Flow and its components
- Improve the Button component
- Change the Buy flow Heroicons pattern, from Solid to Outline
=> Feature Buy Flow

app/components/Button/Button.tsx
Create processing and disabled button variations
`<Button title={'Processing...'} processing />`
`<Button title={'Continue'} disabled />`
=> create processing and disabled button variations

site/app/terms/page.tsx
- Update content, add link tag with the right structure
=> update inline link, to a tag link

app/components/Loading/Loading.tsx, app/components/Select/CurrencySelect.tsx, app/components/Select/TokenSelect.tsx
- Remove "Loading..." message from Loading component
=> remove Loading... message from Loading component

site/app/layout.tsx, site/app/page.tsx
- Add blog link on website header
=> Add blog link on website

app/components/layout.tsx
=> fix navigation-alignment

site/app/layout.tsx, site/app/page.tsx, site/components/DocsHeader.tsx
Update Discord link on all site
From:
https://discord.gg/Wrf9BT8sZN
To:
https://discord.gg/EDHfTfCQ44
=> Update Site Discord link

app/components/Buy/CancelOrderButton/BlockchainCancelButton.tsx, app/components/Buy/CancelOrderButton/CancelOrderButton.tsx, app/components/Buy/CancelOrderButton/CancelReasons.tsx, app/components/Buy/MarkAsPaidButton.tsx, app/components/Buy/ReleaseFundsButton.tsx, app/components/Checkbox/Checkbox.tsx, app/components/Modal/ModalWindow.tsx, app/components/OrdersTable.tsx, app/hooks/index.ts, app/hooks/useCancelReasons.ts, app/models/cancelReasons.ts, app/models/types.ts, app/next.config.js, app/pages/api/orders/[id]/cancel.ts, app/pages/orders/index.tsx
- Add on Cancelation Modal: options to user check, and a input to user describe their motivations to cancel an order
=> Cancelation Modal

app/components/Notifications/TransactionFeedback.tsx, app/contexts/TransactionFeedContext.tsx
Create TransactionFeedback component
How to use it:  
Add `<TransactionFeedback attr />` on screen
=> Create TransactionFeedback component

app/components/Buy/Summary.tsx, app/components/ListsTable.tsx, app/components/layout.tsx, app/models/types.ts, app/pages/buy/[id].tsx
- add % of spot inside price
- merge Available: amount and chain
- add Order time limit column
- change Payment Method: now it shows a border instead of bank simbol 
- button full width
- create a card with secundary infos
=> Ope 197 list table

components/Avatar.tsx
=> fix image squishes

components/Layout/NoAuthLayout.tsx
- Update logo size mobile and desktop
=> update logo size

components/Select/Select.tsx
- Update Select/Dropdown styles
=> update select styles

components/Buy/Filters.tsx, components/Listing/Setup.tsx, components/Select/NetworkSelect.tsx, pages/escrows/index.tsx
- Remove the hardcode element. It's now a flexible option
=> fix extraStyle option

components/Buy/Filters.tsx, pages/trade.tsx, yarn.lock
It will shows an Empty State when the filter returns no results
What's next, for Marcos:
1. Code review
2. Create if statement if no results show it
[Figma Prototype](https://www.figma.com/file/UcMsdFSXAk8nF2gFZjlvNW/OpenPeer-App?type=design&node-id=1361-10532&mode=design&t=JiRTQEe5H8nMHpj0-4)
=> Create filter empty state front-end on trade page

components/TelegramSection.tsx, hooks/useUserProfile.ts, models/types.ts, package-lock.json, pages/[id]/edit.tsx, yarn.lock
This pull request implements a code-based Telegram connection feature and refactors the user profile management system. The main changes include:
1. TelegramSection component:
- Updated to use the new code-based connection method
- Improved error handling and user feedback
- Removed deprecated TelegramConnect component
2. useUserProfile hook:
- Refactored to use async/await for better readability
- Added fetchUserProfile and deleteTelegramInfo functions
- Improved error handling and state management
3. EditProfile component:
- Updated to use the new TelegramSection and useUserProfile hook
- Removed unused code and comments
4. Types:
- Added unique_identifier to User interface
These changes improve the overall functionality and maintainability of the Telegram connection feature and user …
=> Implement code-based Telegram connection and refactor user profile management

components/TelegramSection.tsx, hooks/useUserProfile.ts, pages/[id]/edit.tsx, yarn.lock
This pull request improves the Telegram integration for the OpenPeer application, focusing on better user experience and automatic updates. The main changes include:
1. TelegramSection component (components/TelegramSection.tsx):
- Implemented auto-update functionality to check Telegram connection status periodically.
- Improved handling of Telegram activation and deactivation.
- Removed unused code and simplified the component structure.
2. useUserProfile hook (hooks/useUserProfile.ts):
- Enhanced profile fetching to update all relevant user data, including Telegram information.
- Improved error handling and logging for better debugging.
3. EditProfile component (pages/[id]/edit.tsx):
- Updated props passed to TelegramSection to include the new refreshUserProfile function.
=> Enhance Telegram integration with auto-update and improved user experience

components/Button/Button.tsx, components/Listing/AccountInfo.tsx, components/TelegramSection.tsx, hooks/useUserProfile.ts
This pull request improves the Telegram integration in the frontend, focusing on user experience and reliability. Key changes include:
1. Implemented a rapid refresh mechanism for checking Telegram connection status, providing users with more responsive feedback.
2. Added an alternative method for linking Telegram accounts, giving users a backup option if the primary method fails.
3. Enhanced the TelegramSection component with:
- A countdown timer for status checks
- Improved loading indicators
- A copy-to-clipboard feature for the bot name and start command
4. Optimized the useUserProfile hook for better state management and reduced redundancy.
5. Updated the Button component to support custom background colors and additional CSS classes.
These changes aim to make the Telegram connection …
=> Enhance Telegram integration with rapid refresh and alternative linking method

components/Listing/AccountInfo.tsx, components/TelegramSection.tsx, hooks/useUserProfile.ts, pages/[id]/edit.tsx
This PR refactors the user profile management system and optimizes the Telegram notifications feature. The main changes include:
1. Optimize useUserProfile hook:
- Implement deep comparison in updateUserState using lodash's isEqual
- Simplify fetchUserProfile to reduce unnecessary updates
- Remove individual state values from hook return, adding setter functions instead
2. Refactor AccountInfo and EditProfile components:
- Update to use the revised useUserProfile hook
- Implement local state management for user-related fields
- Add useEffect to update local state when user data changes
3. Enhance TelegramSection component:
- Fix nested button warning by replacing outer button with a div
- Update prop types to match new useUserProfile return value
4. Improve overall performance:
- Reduce …
=> Refactor user profile management and optimize Telegram notifications

components/Input/Input.tsx, components/TelegramSection.tsx, hooks/useUserProfile.ts, models/errors.ts, pages/[id]/edit.tsx, pages/ads/settings.tsx, tailwind.config.cjs
This pull request introduces several improvements to the user profile editing experience:
1. Real-time Updates:
- Implemented instant API updates when editing profile fields.
- Added visual feedback (spinner and "Updating..." text) to indicate when a field is being updated.
- Introduced a debounce mechanism to prevent excessive API calls during rapid typing.
2. Enhanced Error Handling and Validation:
- Improved client-side validation for all profile fields.
- Added more comprehensive error messages for invalid inputs.
- Implemented better handling of API errors.
3. UI/UX Improvements:
- Updated the Input component to show updating status and error messages more clearly.
- Added helper text for various fields to guide users on proper input format.
4. Code Refactoring:
- Refactored the …
=> Enhance User Profile Editing with Real-time Updates and Improved Validation

components/Input/Input.tsx, hooks/useUserProfile.ts, pages/[id]/edit.tsx
This PR enhances the user profile update process and improves input validation across the application. The changes aim to provide a better user experience, reduce unnecessary API calls, and improve error handling.
1. **Debounce Optimization**: Refined the debounce logic in `useUserProfile` hook to reduce unnecessary API calls during rapid user input.
2. **Validation Improvements**: 
- Added length constraints for username and Twitter handle (3-15 characters).
- Implemented stricter validation rules for all user profile fields.
3. **Error Handling**: Enhanced error handling and display for API responses and validation errors.
4. **UI Updates**: 
- Modified input fields to trigger updates on blur instead of on every keystroke.
- Added `maxLength` attribute to relevant input fields.
5. …
=> Improve User Profile Update Functionality and Validation

.gitignore, components/MarginSwitcher.tsx, components/OrdersTable.tsx, pages/orders/index.tsx
This PR introduces several improvements to order management and display features across multiple components. The changes aim to enhance user experience and provide more accurate and up-to-date information.
1. Sort orders in My Trades table:
- Orders are now sorted with the most recent at the top.
2. Save fixed price on ads:
- Fixed prices are now saved rather than reset when editing ads.
3. MarginSwitcher component updates:
- Added "Update to Market Price" button.
- Improved handling of fixed price scenarios.
- Enhanced display of market price information.
4. Orders page improvements:
- Enhanced order filtering logic.
- Implemented sorting of orders by creation date (most recent first).
This PR includes both UI enhancements and backend logic improvements. Please review the changes …
=> Enhance order management and display features

components/Buy/Amount.tsx, components/Buy/EscrowButton/DeploySellerContract.tsx, components/Buy/EscrowButton/EscrowFundsButton.tsx, components/Buy/Payment.tsx, components/DepositButton/DepositFundsButton.tsx, components/EscrowDepositWithdraw.tsx, components/Listing/Details.tsx, components/Listing/FundEscrow.tsx, components/MarginSwitcher.tsx, pages/airdrop.tsx, pages/escrows/index.tsx
The main updates include:
1. Terminology Change: "Escrow Contract" to "Escrow Account"
- Updated all references from "Escrow Contract" to "Escrow Account" throughout the codebase for consistency and clarity.
2. Escrow System Enhancement:
- Implemented a 30-second delay for escrow fund transfers to improve security and prevent potential issues.
- Added logging for escrow creation time and button state for better debugging.
3. User Interface Improvements:
- Inverted colors on the button for updating rate to market price for better visibility.
- Added wallet balance and address display in the Payment component.
- Updated button states and error messages related to escrow operations.
4. New Features:
- Implemented wallet balance fetching using the `useBalance` hook from wagmi.
- Added escrow …
=> Replace Escrow Contract with Escrow Account and Enhance User Experience

components/Buy/Payment.tsx, components/Listing/FundEscrow.tsx
This PR introduces several improvements to the payment and escrow funding processes:
1. Added a "Need to Top Up Your Wallet?" section in both the Payment and FundEscrow components, displaying:
- The user's wallet address
- A copy-to-clipboard button for easy address sharing
- The current wallet balance
2. Implemented a copy-to-clipboard functionality for the wallet address, with a success toast notification.
3. Updated the SVG clipboard icon for better visual consistency.
4. Added the top-up message in the instant escrow flow as well, ensuring consistency across different payment scenarios.
5. Minor UI improvements and code refactoring for better readability and maintainability.
These changes aim to enhance the user experience by making it easier for users to top up their wallets when …
=> Add wallet top-up messages and improve UX for payments

components/Button/EditListButtons.tsx, components/Button/Switcher.tsx, pages/airdrop.tsx
This pull request introduces several enhancements to our ad management system and improves the user interface:
1. Added a new "Share Ad" option:
- Implemented a new option in the EditListButtons component to allow users to share their ads.
- When selected, it copies the ad's URL to the clipboard and shows a success toast.
2. Fixed text visibility issue in Switcher component:
- Resolved an issue where the text color wasn't properly visible in the selected state.
- Removed duplicate Tailwind classes for cleaner code.
3. UI improvements in the Airdrop page:
- Adjusted the background color in certain divs to improve contrast and readability.
These changes improve the overall user experience by making it easier to share ads and navigate the platform. The UI fixes enhance readability and visual …
=> Enhance Ad Management and UI Improvements

components/Select/Select.types.ts, components/Select/TimezoneSelect.tsx, package.json, pages/ads/settings.tsx, utils/timeZoneMapping.ts
This PR addresses issues with timezone handling in our application and improves the user interface for timezone selection. It introduces a translation layer for certain React timezone names to ensure compatibility with Ruby on Rails, and enhances the TimezoneSelect component.
1. Added a timezone mapping utility to translate certain React timezone names to their Ruby on Rails equivalents
2. Updated the TimezoneSelect component to use the new mapping
3. Modified the AdsSettings page to incorporate the improved timezone handling
4. Updated type definitions for better TypeScript support
5. Changed the development server port to 3001
- `utils/timeZoneMapping.ts`: Contains the mapping between React and Ruby on Rails timezone names
- `TimezoneSelect.tsx`: Now uses the timezone mapping for better …
=> Enhance Timezone Handling and User Interface

components/AddressTooltip.tsx, components/Listing/Details.tsx, components/Select/TimezoneSelect.tsx, hooks/useUserProfile.ts, pages/[id]/index.tsx, pages/ads/index.tsx, pages/ads/settings.tsx, pages/api/lists/ads.ts, pages/api/user_relationships/[relationship_type]/[target_user_id].ts, pages/api/user_relationships/index.ts, pages/api/user_search/[address].ts, pages/api/users/[address].ts, pages/api/utils/utils.ts
This PR implements user relationships functionality and includes several UI improvements across the application. Key changes include:
1. User Relationships:
- Added API routes for managing user relationships (trust/block)
- Implemented frontend components for displaying and managing trusted/blocked users
2. UI Improvements:
- Created an AddressTooltip component for better address display
- Updated the Ads page to use profile page logic for fetching user's ads
- Improved timezone selection in user settings
3. Bug Fixes and Optimizations:
- Fixed issues with time selection in ad settings
- Ensured 0 value in "from" time is shown as 00:00 in frontend
- Added timeout for user not found error messages
- Removed the need to always update email in profile updates
4. Code Refactoring:
- …
=> Implement user relationships functionality and various UI improvements

components/BlockedUsers.tsx, components/Listing/Details.tsx, components/TrustedUsers.tsx, hooks/useUserProfile.ts, pages/[id]/edit.tsx, pages/api/user_profiles/[address].ts
This pull request introduces significant improvements to user profile management, focusing on the implementation of trusted and blocked users functionality. The changes span across multiple components and API endpoints, enhancing both the user interface and backend logic.
Key changes:
1. New Components:
- Added `TrustedUsers` component for managing trusted traders
- Added `BlockedUsers` component for managing blocked users
2. Profile Edit Page (`pages/[id]/edit.tsx`):
- Integrated `TrustedUsers` and `BlockedUsers` components
- Improved error handling and field validation
3. API Enhancements:
- Updated user profile API (`pages/api/user_profiles/[address].ts`) to handle PATCH requests
- Improved error handling and response formatting in the API
4. User Profile Hook …
=> Enhance user profile management with trusted and blocked users

components/Listing/Details.tsx, components/Listing/Summary.tsx, pages/ads/settings.tsx, pages/api/lists/[id].ts, pages/api/lists/ads.ts, pages/api/user_profiles/[address].ts, pages/api/user_relationships/[relationship_type]/[target_user_id].ts, pages/api/user_relationships/index.ts
This pull request addresses inconsistencies in authentication handling across various API routes in the frontend codebase. The primary goal is to standardize the use of JWT tokens for authentication to ensure seamless integration with the backend and prevent mismatches.
**Key Changes:**
1. **Introduced a Utility Function for Token Extraction:**
- Added `getTokenFromHeader` utility function to consistently extract the JWT token from the `Authorization` header in the format `Bearer <jwt_token>`.
- This function is used across multiple API handlers to standardize token extraction.
2. **Updated API Routes to Use JWT Tokens:**
- **`pages/api/lists/[id].ts`:**
- Refactored to include the JWT token in the `Authorization` header for all requests (`GET`, `PUT`, `DELETE`).
- Removed direct …
=> Standardize Authentication Handling Across API Routes to Use JWT Tokens

components/BlockedUsers.tsx, components/Button/EditListButtons.tsx, components/HiddenBadge.tsx, components/Listing/AccountInfo.tsx, components/ListsTable.tsx, components/TrustedUsers.tsx, pages/ads/index.tsx, pages/api/banks.ts, pages/api/lists/ads.ts, pages/api/user_relationships/[relationship_type]/[target_user_id].ts, pages/api/user_relationships/index.ts
This PR introduces several important changes to improve authentication, user relationships handling, and ad display functionality:
- Replaced `Authorization: Bearer ${address}` with `X-User-Address: ${address}` header across API routes
- Updated API routes to use the new authentication method
- Refactored client-side code to use the new authentication headers
- Improved handling of trusted and blocked user lists
- Added checks to prevent users from being in both trusted and blocked lists simultaneously
- Updated API routes for user relationships to use the new authentication method
- Modified the `/ads` page to fetch and display all ads, including hidden ones
- Added a `HiddenBadge` component to visually indicate hidden ads
- Updated the `ListsTable` component to handle and display hidden …
=> Refactor authentication, enhance user relationships, and improve ad display

pages/api/generate_talkjs_token.ts, providers/TalkProvider.tsx
This pull request addresses an authentication error and enhances the TalkJS integration in our application. 
Here are the key changes:
1. Fixed an authentication error by updating the TalkJS app ID environment variable.
2. Improved error handling and logging in the TalkJS token generation API.
3. Enhanced the TalkProvider component to handle authentication more robustly:
- Added proper error checking for auth tokens
- Improved user details fetching with authentication headers
- Added more detailed logging for debugging purposes
4. Updated the syncUser function to ensure it always has valid data
5. Improved the rendering logic in TalkProvider to handle cases where TalkJS is not configured
These changes should resolve the authentication issues and provide a more stable integration with …
=> Fix authentication error and improve TalkJS integration

hooks/useUserProfile.ts, pages/api/user_profiles/[address].ts, pages/trade.tsx
- Added detailed logging to the  function to trace the filtering of ads.
- Logs evaluation of each ad including seller ID, trust status, and reasons for inclusion or exclusion.
- Logs total ads fetched and filtered ads count for better visibility.
- Ensured that seller IDs are consistently treated as numbers to prevent type mismatches.
- Improved exclusion logic by clearly distinguishing between blocked users and trusted-only ads.
- Refined the logic for handling trusted relationships ( and ) for more accurate ad filtering.
=> Enhance logging and fix ID handling in ad filtering logic
